<a href="https://colab.research.google.com/github/mgmeti/tensorflow_practice/blob/main/tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# pip install tensorflow

Chapter 2:
<br>
Tensorflow for Dummies

In [24]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

# create tensor
msg = tf.strings.join(["Hello", "Tensorflow!"],  separator=" ")
# Launch session
with tf.compat.v1.Session()  as sess:
    # print(sess.run(msg))
    hello = tf.constant('hello world')
    print(sess.run(hello))
# Note: TF1.x version
# msg = tf.constant('Hello, TensorFlow!')
# Note: TF2.x version
# No need for session to create
tf.print(msg)

b'hello world'
Hello Tensorflow!


Chapter 3:
*   The constant function
*   Hey




In [29]:
t1 = tf.constant([1.5, 2.5, 3.5])
tf.print(t1)

t2 = tf.constant([['b', 'b'], ['b', 'b']])
tf.print(t2)

t3 = tf.constant([4, 2, 5], tf.int16, [3], 'Const')
tf.print(t3)

[1.5 2.5 3.5]
[["b" "b"]
 ["b" "b"]]
[4 2 5]


In [31]:
#@title zeros, ones, and fill
zero_tensor = tf.zeros([3])
tf.print(zero_tensor)

one_tensor = tf.ones([4, 4])
tf.print(one_tensor)

fill_tensor = tf.fill([2, 2, 3], 81.0)
tf.print(fill_tensor)

[0 0 0]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[[81 81 81]
  [81 81 81]]

 [[81 81 81]
  [81 81 81]]]


In [32]:
#@title Creating sequences
lin_tensor = tf.linspace(5., 9., 5)
tf.print("Linear space generates a sequence between start and end:", lin_tensor)

range_tensor_start = tf.range(3., 7., delta=0.5)
tf.print("Range tensor generates a sequence between start and end:", range_tensor_start)


range_tensor = tf.range(1.5, delta=.5)
tf.print("Range tensor generates a sequence between 0 and end:", range_tensor_start)



Linear space generates a sequence between start and end: [5 6 7 8 9]
Range tensor generates a sequence between start and end: [3 3.5 4 ... 5.5 6 6.5]
Range tensor generates a sequence between 0 and end: [3 3.5 4 ... 5.5 6 6.5]


In [39]:
#@title Tensors from Random Values
rnd_ints = tf.random.normal([10], dtype=tf.float64)
tf.print("Generate 10 random normal values:", rnd_ints)
# reference: https://stackoverflow.com/questions/59953127/tensorflow-2-1-0-has-no-attribute-random-normal



Generate 10 random normal values: [-0.45381445656212582 -0.477816262363832 -1.1035295553402811 ... 1.3396439451975761 -0.15198366778115996 -0.26530763974034866]


In [57]:
#@title Transforming Tensors
vec = tf.constant([1., 2., 3., 4., 5., 6.])
mat = tf.reshape(vec, [2, 3])
tf.print("1D Vector:", vec)
tf.print("2D Vector (Matrix):", mat)

print("_"*20)

mat  = tf.constant([[1., 2., 3.], [4., 5., 6.]])
print("matrix shape:", mat.shape)
rev_mat = tf.reverse(mat, [0])
tf.print("Matrix", mat)
tf.print("Reversed matrix", rev_mat)

print("_"*20)

rev_mat = tf.reverse(mat, [1])
tf.print("Matrix", mat)
tf.print("Reversed matrix", rev_mat)

print("_"*20)

rev_mat = tf.reverse(mat, [0, 1])
tf.print("Matrix", mat)
tf.print("Reversed matrix", rev_mat)
mat = tf.constant([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
slice_mat = tf.slice(mat, [1, 0], [2, 2])
tf.print("3-x-3 matrix:", mat)
tf.print("2-x-2 matrix is sliced from 3-x-3 starting form element at [1, 1]:", slice_mat)
t1 = tf.constant([1., 2.])
tf.print(t1)

t2 = tf.constant([3., 4.])
tf.print(t2)
t3 = tf.constant([5., 6.])
tf.print(t3)

print('_' * 20)
t4 = tf.stack([t1, t2, t3])
print("stacked tensor:", t4)

1D Vector: [1 2 3 4 5 6]
2D Vector (Matrix): [[1 2 3]
 [4 5 6]]
____________________
matrix shape: (2, 3)
Matrix [[1 2 3]
 [4 5 6]]
Reversed matrix [[4 5 6]
 [1 2 3]]
____________________
Matrix [[1 2 3]
 [4 5 6]]
Reversed matrix [[3 2 1]
 [6 5 4]]
____________________
Matrix [[1 2 3]
 [4 5 6]]
Reversed matrix [[6 5 4]
 [3 2 1]]
3-x-3 matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
2-x-2 matrix is sliced from 3-x-3 starting form element at [1, 1]: [[4 5]
 [7 8]]
[1 2]
[3 4]
[5 6]
____________________
stacked tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)
